name: konyak_cli
description: CLI backend contract for Konyak.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.4

dependencies:
  args: ^2.7.0
  crypto: ^3.0.7
  fast_immutable_collections: ^11.2.0
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  json_schema: ^5.2.2

dev_dependencies:
  build_runner: ^2.15.0
  custom_lint: ^0.8.1
  freezed: ^3.2.3
  konyak_lints:
    path: ../../tools/konyak_lints
  lints: ^6.0.0
  test: ^1.30.0
